version: "3"
services:
    project:
        build: .
        ports:
            - "3000:3000"
        links:
            - mysql
            # - proxy
            - nginx
        networks:
            - backnet
            - frontnet

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        expose:
            - "3306"
        volumes:
            - /home/ubuntu/db/data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro # 時間和外面相通
        networks:
            - backnet
    # proxy:
    #     build: proxy
    #     restart: always
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - /etc/localtime:/etc/localtime:ro # 時間和外面相通
    #     networks:
    #         - frontnet

    nginx:
        image: nginx:1.15-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./proxy/nginx:/etc/nginx/conf.d #.conf互通
            - ./proxy/certbot/conf:/etc/letsencrypt
            - ./proxy/certbot/www:/var/www/certbot
            - /etc/localtime:/etc/localtime:ro # 時間和外面相通
        networks:
            - backnet
        # This makes nginx reload its configuration (and certificates) every six hours (Automatic Certificate Renewal)
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
    certbot:
        image: certbot/certbot:v0.36.0
        volumes:
            - ./proxy/certbot/conf:/etc/letsencrypt
            - ./proxy/certbot/www:/var/www/certbot
        # check if your certificate is up for renewal every 12 hours (Automatic Certificate Renewal)
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
    backnet:
    frontnet:
volumes:
    data:
