version: "3"
services:
    project:
        build: .
        ports:
            - "3000:3000"
        links:
            - mysql
            - nginx
            # - proxy
        networks:
            - backnet
            - frontnet

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        expose:
            - "3306"
        volumes:
            - /home/ubuntu/db/data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro # 時間和外面相通
        networks:
            - backnet

    proxy:
        build: proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - /etc/localtime:/etc/localtime:ro # 時間和外面相通
        networks:
            - frontnet

networks:
    backnet:
    frontnet:
volumes:
    data:
