version: "3"
services:
    project:
        build: .
        ports:
            - "3000:3000"
        links:
            - taipei-day-trip-website_mysql_1
        networks:
            - second-stage-project

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - /home/ubuntu/db/data:/var/lib/mysql
        networks:
            - second-stage-project

networks:
    second-stage-project:
volumes:
    data:
