version: "3"
services:
    project:
        build: .
        ports:
            - "3000:3000"
        links:
            - mysql
        networks:
            - second-stage-project

    mysql:
        image: mysql
        ports: ["3306"]
        networks:
            - second-stage-project

networks:
    second-stage-project:
