version: "3"
services:
    project:
        build: .
        ports:
            - "3000:3000"
        links:
            - mysql
        networks:
            - second-stage-project

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        ports: "3306:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql
        networks:
            - second-stage-project

networks:
    second-stage-project:
volumes:
    my-db:
